language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli bower
- bower install
notifications:
  irc:
    channels:
    - chat.freenode.net#hoodie
  use_notice: true
  skip_join: true
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: zR8Ajapr0q7kQngtPHNduxeQFPhtt9txalgoP+JX1yGJXRNBFCWos3qdD6XZQ6HKfSMA366pZWluSIXxjXu6AKv6ljFmpKzS+uQnJi87ifik5OmEej8aWzNY17ddvlTKZFyM2RL21f4lKpjGbaS02kYR6bxxlaE4DFkva7bT/eE=
env:
  global:
  - secure: A2PGKcshD1Q+r6sbwmXusMgvZHAWBI/Vg8xMuoHC7Dw8xejMcs4VjDeMTrkXCotylTTyv+K44/DMAKohdmI/ajWh9zVtwdkYRXBG8bk4Y6TaIPvJ4fm7iBvR0l4XB/SQrpJjJTBhqkGxAnCP7tBjP952EbxkPjZGNHOEd305buU=
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
